### ISSUE TITLE
Additional documents/publications to better understand the PEPMatch tools

### ISSUE THREAD

**Issue by ravinpoudel** [IEDB/PEPMatch#1]
Wondering if there is/are additional documents/publications that will allow user to better understand how the PEPMatch create a db and does the matching tasks?

**Comment by danielmarrama** [comment]
Hi, the README has been updated a lot and should be enough to have you run your own job. You can also use the command line now to preprocess and match. We are currently in the process of a publication for the tool. Thanks for your interest.
