### ISSUE TITLE
Preprocessor and Matcher

### ISSUE THREAD

**Issue by HA1-biocopy** [IEDB/PEPMatch#18]
In all given examples there is a preprocessing step, yet the outcome of that step not used in the matcher? can you explain please?

**Comment by dmx2** [comment]
The preprocessed files automatically get generated in the current working directory unless specified with `preprocessed_files_path` in either the preprocessing step or the matching step. By passing `max_mismatches` and `k` values to matcher, it will use the appropriate preprocessed files needed to run the search.
