### ISSUE TITLE
Species Questions About reference proteome

### ISSUE THREAD

**Issue by peomelo** [IEDB/PEPMatch#4]
Hi, I want to use the antigenic peptide of a virus to compare the proteome sequence of another virus. My results are all NaN. I see Available proteomes include: human, mouse, cow, dog, horse, pig, rabbit, rat. I would like to ask if I can use Pepmatch to compare the homology of two viruses?

**Comment by danielmarrama** [comment]
@peomelo Of course! Download the proteome for the virus to search in from UniProt. Preprocess with `Preprocessor` as shown in the example code. And then run `Matcher` using your antigenic peptide(s). Make sure you pass `max_mismatches` to some allow residue substitution, we typically recommend 2 mismatches for 8-12-mer peptides and 3 mismatches for 12-18-mer peptides.
