### ISSUE TITLE
Fail to import hamming 

### ISSUE THREAD

**Issue by Hayfabm** [IEDB/PEPMatch#6]
Hi, 

I tried to use the following script to get the mismatching output:
```
from pepmatch import Preprocessor, Matcher

Preprocessor('proteomes/human.fasta').pickle_proteome(k = 3)

Matcher( # 3 mismatches, k = 3
  'queries/neoepitopes-test.fasta', 'proteomes/human.fasta', 3, 3
).match()
```
I got an issue when importing hamming says  `ModuleNotFoundError: No module named 'pepmatch.hamming'
`
Is there anything to fix? 

Thanks a lot,

**Comment by danielmarrama** [comment]
Hello, @Hayfabm, which OS are you using? Did you `pip install pepmatch` or trying running from the source code?

**Comment by danielmarrama** [comment]
Ok, I see. So, there is a C extension called `hamming.c` which builds when you `pip install pepmatch` - so it's highly recommended you do that. Try that and see if you can get it working.
